eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost 
microservice:
   payment-service:
      endpoinsts:
         endpoint:
            uri: http://PAYMENT-SERVICE/payment/doPayment
            
   order-service:
      endpoinsts:
         endpoint:
            uri: http://ORDER-SERVICE/order/bookOrder  
